# Generated by Django 5.2.3 on 2025-06-24 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_consent_date_customuser_store_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_credit_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
