# Generated by Django 5.2.3 on 2025-06-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='dialect',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='output_text',
        ),
    ]
